#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
# Ignore ambient overrides. Authored stages may assign one exact literal path.
ENV_FILE=".env"
_WIZARD_AUTHORIZED_BASE=$(pwd -P) || exit 1
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)
_WIZARD_CAPTURED_VALUE="" # fixed return channel for the most recent capture

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# _dotenv_key_is_reserved — keep captured values away from shell/library state.
_dotenv_key_is_reserved() {
  case "$1" in
    PATH|ENV|ENV_FILE|GITHUB_REPO|IFS|CDPATH|SHELLOPTS|BASH_ENV|PWD|OLDPWD|HOME|USER|LOGNAME|SHLVL|TMPDIR|\
    BASH*|_WIZARD_*|BOLD|DIM|RESET|BLUE|GREEN|YELLOW|RED|TOTAL_STAGES|_STAGE_INDEX|\
    WRITTEN_ENV|WRITTEN_SECRET|SKIPPED|COMP_*|DIRSTACK|EUID|FUNCNAME|GROUPS|HOSTNAME|HOSTTYPE|\
    LINENO|MACHTYPE|OPTARG|OPTERR|OPTIND|OSTYPE|PIPESTATUS|PPID|RANDOM|SECONDS|UID)
      return 0
      ;;
  esac
  return 1
}

# _dotenv_*_is_safe — keep the raw KEY=VALUE serializer unambiguous.
_dotenv_key_is_safe() {
  local pattern='^[A-Za-z_][A-Za-z0-9_]*$'
  [[ "$1" =~ $pattern ]] || return 1
  ! _dotenv_key_is_reserved "$1"
}

_dotenv_value_is_safe() {
  local pattern='^[A-Za-z0-9_./:@%+,=?-]*$'
  [[ "$1" =~ $pattern ]]
}

# _wizard_git — discover the target's repository from its -C directory, not
# from inherited worktree, index, object, ceiling, or config overrides.
_wizard_git() {
  env \
    -u GIT_DIR \
    -u GIT_WORK_TREE \
    -u GIT_COMMON_DIR \
    -u GIT_INDEX_FILE \
    -u GIT_OBJECT_DIRECTORY \
    -u GIT_ALTERNATE_OBJECT_DIRECTORIES \
    -u GIT_CEILING_DIRECTORIES \
    -u GIT_DISCOVERY_ACROSS_FILESYSTEM \
    -u GIT_CONFIG \
    -u GIT_CONFIG_SYSTEM \
    -u GIT_CONFIG_GLOBAL \
    -u GIT_CONFIG_NOSYSTEM \
    -u GIT_CONFIG_PARAMETERS \
    -u GIT_CONFIG_COUNT \
    GIT_CONFIG_NOSYSTEM=1 \
    GIT_CONFIG_GLOBAL=/dev/null \
    GIT_CONFIG_COUNT=0 \
    git "$@"
}

# _env_target_is_ignored — inside a Git worktree, require both the final path
# and a representative transaction path to be ignored before reads or writes.
_env_target_is_ignored() {
  local target="$1" parent
  parent=${target%/*}
  command -v git >/dev/null 2>&1 || return 0
  _wizard_git -C "$parent" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  if ! _wizard_git -C "$parent" check-ignore -q -- "$target"; then
    warn "refusing non-ignored ENV_FILE in Git worktree: $target" >&2
    return 1
  fi
  if ! _wizard_git -C "$parent" check-ignore -q -- "${target}.tmp.probe"; then
    warn "refusing non-ignored ENV_FILE temporary path in Git worktree: ${target}.tmp.probe" >&2
    return 1
  fi
}

# _env_actual_temp_is_ignored — a probe can match a narrower ignore rule than
# mktemp's random name, so verify the created path before writing any value.
_env_actual_temp_is_ignored() {
  local temp="$1" parent
  parent=${temp%/*}
  command -v git >/dev/null 2>&1 || return 0
  _wizard_git -C "$parent" rev-parse --is-inside-work-tree >/dev/null 2>&1 || return 0
  if ! _wizard_git -C "$parent" check-ignore -q -- "$temp"; then
    warn "refusing non-ignored ENV_FILE actual temporary path in Git worktree: $temp" >&2
    return 1
  fi
}

# _validated_env_target — print the absolute ENV_FILE target after proving it
# stays below the physical startup directory and has no symlinked components.
_validated_env_target() {
  local raw="$ENV_FILE" target parent canonical_parent cursor remaining component leaf
  if [[ -z "$raw" || "$raw" == *$'\n'* || "$raw" == *$'\r'* ]]; then
    warn "refusing invalid ENV_FILE path" >&2
    return 1
  fi
  if [[ "$raw" =~ (^|/)\.\.?(/|$) ]] || [[ "$raw" == */ ]]; then
    warn "refusing ENV_FILE traversal: $raw" >&2
    return 1
  fi

  if [[ "$raw" == /* ]]; then
    target="$raw"
  elif [[ "$_WIZARD_AUTHORIZED_BASE" == / ]]; then
    target="/$raw"
  else
    target="$_WIZARD_AUTHORIZED_BASE/$raw"
  fi
  if [[ "$_WIZARD_AUTHORIZED_BASE" != / ]]; then
    case "$target" in
      "$_WIZARD_AUTHORIZED_BASE"/*) ;;
      *) warn "refusing ENV_FILE outside startup directory: $raw" >&2; return 1 ;;
    esac
  fi

  parent=${target%/*}
  leaf=${target##*/}
  [[ -n "$leaf" ]] || { warn "refusing invalid ENV_FILE path: $raw" >&2; return 1; }
  cursor="$_WIZARD_AUTHORIZED_BASE"
  remaining=${parent#"$_WIZARD_AUTHORIZED_BASE"}
  remaining=${remaining#/}
  while [[ -n "$remaining" ]]; do
    component=${remaining%%/*}
    if [[ "$remaining" == */* ]]; then remaining=${remaining#*/}; else remaining=""; fi
    [[ -n "$component" ]] || continue
    if [[ "$cursor" == / ]]; then cursor="/$component"; else cursor="$cursor/$component"; fi
    if [[ -L "$cursor" ]]; then
      warn "refusing ENV_FILE symlink component: $cursor" >&2
      return 1
    fi
    if [[ ! -d "$cursor" ]]; then
      warn "refusing missing or non-directory ENV_FILE parent: $cursor" >&2
      return 1
    fi
  done

  canonical_parent=$(cd -P -- "$parent" 2>/dev/null && pwd -P) || {
    warn "refusing unresolved ENV_FILE parent: $parent" >&2
    return 1
  }
  if [[ "$_WIZARD_AUTHORIZED_BASE" != / ]]; then
    case "$canonical_parent" in
      "$_WIZARD_AUTHORIZED_BASE"|"$_WIZARD_AUTHORIZED_BASE"/*) ;;
      *) warn "refusing ENV_FILE parent outside startup directory: $parent" >&2; return 1 ;;
    esac
  fi

  if [[ -L "$target" ]]; then
    warn "refusing ENV_FILE symlink: $target" >&2
    return 1
  fi
  if [[ -e "$target" ]] && [[ ! -f "$target" ]]; then
    warn "refusing non-regular ENV_FILE: $target" >&2
    return 1
  fi
  _env_target_is_ignored "$target" || return 1
  printf '%s' "$target"
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  local key="$1" target checked_target line value
  _dotenv_key_is_safe "$key" || {
    if _dotenv_key_is_reserved "$key"; then
      warn "refusing reserved dotenv key: $key" >&2
    else
      warn "refusing invalid dotenv key: $key" >&2
    fi
    return 2
  }
  target=$(_validated_env_target) || return 2
  [[ -f "$target" ]] || return 1
  checked_target=$(_validated_env_target) || return 2
  [[ "$checked_target" == "$target" ]] || return 2
  line=$(grep -E "^${key}=" "$target" | tail -n1) || return 1
  value=${line#*=}
  _dotenv_value_is_safe "$value" || { warn "refusing unsafe existing dotenv value for $key" >&2; return 2; }
  printf '%s' "$value"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input existing_status
  _dotenv_key_is_safe "$key" || {
    if _dotenv_key_is_reserved "$key"; then
      warn "refusing reserved dotenv key: $key"
    else
      warn "refusing invalid dotenv key: $key"
    fi
    return 1
  }
  _validated_env_target >/dev/null || return 1
  if current=$(_existing "$key"); then
    :
  else
    existing_status=$?
    [[ "$existing_status" -eq 1 ]] || return "$existing_status"
    current=""
  fi
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  _WIZARD_CAPTURED_VALUE="$input"
  # Keep the historical ask KEY API for valid, non-reserved dotenv keys. The
  # fixed channel above is available to stages that do not need a dynamic
  # assignment (and is itself protected by the _WIZARD_* reservation).
  printf -v "$key" '%s' "$_WIZARD_CAPTURED_VALUE"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input existing_status
  _dotenv_key_is_safe "$key" || {
    if _dotenv_key_is_reserved "$key"; then
      warn "refusing reserved dotenv key: $key"
    else
      warn "refusing invalid dotenv key: $key"
    fi
    return 1
  }
  _validated_env_target >/dev/null || return 1
  if current=$(_existing "$key"); then
    :
  else
    existing_status=$?
    [[ "$existing_status" -eq 1 ]] || return "$existing_status"
    current=""
  fi
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  _WIZARD_CAPTURED_VALUE="$input"
  # Keep the historical ask_secret KEY API for valid, non-reserved dotenv
  # keys; callers may instead consume the fixed capture channel.
  printf -v "$key" '%s' "$_WIZARD_CAPTURED_VALUE"
}

# _write_env_file KEY VALUE — atomically upsert KEY=VALUE into ENV_FILE. The
# child process owns its cleanup traps, so authored stage traps stay untouched.
_write_env_file() (
  local key="$1" value="$2" status target checked_target
  _WIZARD_ENV_TMP=""

  _write_env_cleanup() {
    if [[ -n "${_WIZARD_ENV_TMP:-}" ]]; then
      rm -f -- "$_WIZARD_ENV_TMP" || true
      _WIZARD_ENV_TMP=""
    fi
  }

  trap '_write_env_cleanup' EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM

  _dotenv_key_is_safe "$key" || { warn "refusing invalid dotenv key: $key"; return 1; }
  _dotenv_value_is_safe "$value" || { warn "refusing unsafe dotenv value for $key"; return 1; }
  target=$(_validated_env_target) || return 1

  checked_target=$(_validated_env_target) || return 1
  [[ "$checked_target" == "$target" ]] || return 1
  if _WIZARD_ENV_TMP=$(mktemp "${target}.tmp.XXXXXX"); then
    :
  else
    status=$?
    return "$status"
  fi
  if [[ -z "$_WIZARD_ENV_TMP" ]]; then
    return 1
  fi
  _env_actual_temp_is_ignored "$_WIZARD_ENV_TMP" || return 1
  if chmod 600 "$_WIZARD_ENV_TMP"; then
    :
  else
    status=$?
    return "$status"
  fi
  checked_target=$(_validated_env_target) || return 1
  [[ "$checked_target" == "$target" ]] || return 1
  if [[ -f "$target" ]]; then
    if grep -vE "^${key}=" "$target" > "$_WIZARD_ENV_TMP"; then
      :
    else
      status=$?
      if [[ "$status" -ne 1 ]]; then
        return "$status"
      fi
    fi
  fi
  if printf '%s=%s\n' "$key" "$value" >> "$_WIZARD_ENV_TMP"; then
    :
  else
    status=$?
    return "$status"
  fi
  checked_target=$(_validated_env_target) || return 1
  [[ "$checked_target" == "$target" ]] || return 1
  if mv "$_WIZARD_ENV_TMP" "$target"; then
    _WIZARD_ENV_TMP=""
  else
    status=$?
    return "$status"
  fi
)

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" status
  if ! _dotenv_key_is_safe "$key"; then
    if _dotenv_key_is_reserved "$key"; then
      warn "refusing reserved dotenv key: $key"
    else
      warn "refusing invalid dotenv key: $key"
    fi
    return 1
  fi
  if _write_env_file "$key" "$value"; then
    :
  else
    status=$?
    return "$status"
  fi
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# _github_repo — return the exact repo configured by the authored stages, but
# only when gh is available and authenticated. Never infer a write target from
# the current directory.
_github_repo() {
  local repo="${GITHUB_REPO:-}"
  [[ -n "$repo" ]] || return 1
  command -v gh >/dev/null 2>&1 || return 1
  gh auth status >/dev/null 2>&1 || return 1
  printf '%s' "$repo"
}

# set_secret NAME VALUE — confirm and set a GitHub Actions repo secret via gh.
# Falls back to a warning (and records it) unless the repo and gh are ready.
set_secret() {
  local name="$1" value="$2" repo
  if ! repo=$(_github_repo); then
    SKIPPED+=("GitHub secret $name (set GITHUB_REPO and authenticate gh)")
    warn "skipped GitHub secret $name — GITHUB_REPO or authenticated gh missing"
    return
  fi
  if ! confirm "Set or overwrite GitHub secret $name in $repo?"; then
    SKIPPED+=("GitHub secret $name in $repo (declined)")
    warn "skipped GitHub secret $name — not approved"
    return
  fi
  if printf '%s' "$value" | gh secret set "$name" --repo "$repo" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ set%s GitHub secret %s in %s\n' "$GREEN" "$RESET" "$name" "$repo"
    return
  fi
  SKIPPED+=("GitHub secret $name in $repo (gh write failed)")
  warn "skipped GitHub secret $name — gh write failed"
}

# set_var NAME VALUE — confirm and set a GitHub Actions repo variable.
set_var() {
  local name="$1" value="$2" repo
  if ! repo=$(_github_repo); then
    SKIPPED+=("GitHub variable $name (set GITHUB_REPO and authenticate gh)")
    warn "skipped GitHub variable $name — GITHUB_REPO or authenticated gh missing"
    return
  fi
  if ! confirm "Set or overwrite GitHub variable $name in $repo?"; then
    SKIPPED+=("GitHub variable $name in $repo (declined)")
    warn "skipped GitHub variable $name — not approved"
    return
  fi
  if gh variable set "$name" --body "$value" --repo "$repo" >/dev/null 2>&1; then
    printf '  %s✓ set%s GitHub variable %s in %s\n' "$GREEN" "$RESET" "$name" "$repo"
    return
  fi
  SKIPPED+=("GitHub variable $name in $repo (gh write failed)")
  warn "skipped GitHub variable $name — gh write failed"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1
GITHUB_REPO="" # Set exact OWNER/REPO or HOST/OWNER/REPO for GitHub writes.

banner "Stripe setup"

# ── Example stage: replace with your real steps ───────────────────────────
stage "Stripe — API keys"
say "We'll grab your Stripe test keys and store them for local dev + CI."
open_url "https://dashboard.stripe.com/test/apikeys"
step "On the API keys page, copy the Publishable key (starts pk_test_)."
ask STRIPE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Click 'Reveal test key' on the Secret key row, then copy it."
ask_secret STRIPE_SECRET_KEY "Paste the secret key:"
write_env STRIPE_PUBLISHABLE_KEY "$STRIPE_PUBLISHABLE_KEY"
write_env STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"
set_secret STRIPE_SECRET_KEY "$STRIPE_SECRET_KEY"   # CI needs this one
# ──────────────────────────────────────────────────────────────────────────

finish
