package agentconfig

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"ai-agent-config/hooks/internal/codexconfig"
)

const managedHeader = "# Generated by ai-agent-config. Do not edit directly; edit config/codex-agents/*.toml.\n"

type Config struct {
	RepoRoot        string
	Home            string
	CodexHome       string
	ClaudeHome      string
	OpenCodeHome    string
	AntigravityHome string
	AgentsHome      string
	Out             io.Writer
	Now             func() time.Time
}

func NewConfig(repoRoot string, out io.Writer) (Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Config{}, err
	}
	if repoRoot == "" {
		repoRoot, err = defaultRepoRoot()
		if err != nil {
			return Config{}, err
		}
	}
	repoRoot, err = filepath.Abs(repoRoot)
	if err != nil {
		return Config{}, err
	}
	if out == nil {
		out = os.Stdout
	}
	antigravityHome := envDefault("ANTIGRAVITY_HOME", "")
	if antigravityHome == "" {
		antigravityHome = envDefault("GEMINI_HOME", filepath.Join(home, ".gemini"))
	}
	return Config{
		RepoRoot:        repoRoot,
		Home:            home,
		CodexHome:       envDefault("CODEX_HOME", filepath.Join(home, ".codex")),
		ClaudeHome:      envDefault("CLAUDE_HOME", filepath.Join(home, ".claude")),
		OpenCodeHome:    envDefault("OPENCODE_HOME", filepath.Join(home, ".config", "opencode")),
		AntigravityHome: antigravityHome,
		AgentsHome:      envDefault("AGENTS_HOME", filepath.Join(home, ".agents")),
		Out:             out,
		Now:             time.Now,
	}, nil
}

func (c Config) Install() error {
	c.println("Installing AI agent configuration...")
	c.printf("Config directory: %s\n", c.RepoRoot)
	c.println("")
	c.println("Creating symlinks...")

	configured := 0
	if dirExists(c.CodexHome) {
		configured++
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.CodexHome, "AGENTS.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Codex home not found, skipping: %s\n", c.CodexHome)
	}
	if dirExists(c.ClaudeHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.ClaudeHome, "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "CLAUDE.md"), filepath.Join(c.ClaudeHome, "CLAUDE.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Claude home not found, skipping: %s\n", c.ClaudeHome)
	}
	if dirExists(c.OpenCodeHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.OpenCodeHome, "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.OpenCodeHome, "AGENTS.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - OpenCode home not found, skipping: %s\n", c.OpenCodeHome)
	}
	if dirExists(c.AntigravityHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.AntigravityHome, "antigravity-cli", "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.AntigravityHome, "GEMINI.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Antigravity CLI/Gemini home not found, skipping: %s\n", c.AntigravityHome)
	}

	c.println("")
	if configured == 0 {
		c.println("Warning: no supported home directories were found. No symlinks were created.")
	}
	if dirExists(c.CodexHome) {
		c.println("")
		if err := c.SetupCodexConfig(); err != nil {
			c.println("Warning: Codex base config setup failed; continuing with agent and shell setup.")
			c.println("         Run scripts/setup_codex_config.sh after resolving the reported config issue.")
		}
		c.println("")
		if err := c.SetupCodexAgents(); err != nil {
			return err
		}
		c.println("")
		if err := c.SetupCodexShell(); err != nil {
			return err
		}
	}
	if dirExists(c.ClaudeHome) {
		c.println("")
		if err := c.SetupClaudeAgents(); err != nil {
			return err
		}
	}
	c.println("Installation complete.")
	c.println("")
	c.println("Next steps:")
	c.println("   1. Read README.md for usage.")
	c.println("   2. Update skills, config/codex-agents, and repo-local plugins as needed.")
	c.println("   3. Run this script again after pulling updates.")
	return nil
}

func (c Config) SetupCodexConfig() error {
	c.println("Applying Codex base config setup...")
	result, err := codexconfig.Apply(c.CodexHome, c.Now())
	if err != nil {
		c.printf("   ! Codex base config setup failed: %v\n", err)
		return err
	}
	if result.Changed {
		if result.BackupPath != "" {
			c.printf("   + Updated %s (backup: %s)\n", result.Path, result.BackupPath)
		} else {
			c.printf("   + Created %s\n", result.Path)
		}
	} else {
		c.printf("   = %s already has workspace-git permissions\n", result.Path)
	}
	c.println("")
	c.println("Codex base config setup complete.")
	return nil
}

func (c Config) SetupCodexAgents() error {
	c.println("Applying Codex shared skills + standalone role-file setup...")
	if err := os.MkdirAll(c.CodexHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking shared Codex skills into ~/.agents/skills...")
	if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.AgentsHome, "skills")); err != nil {
		return err
	}
	c.println("")
	c.println("Generating standalone Codex role files into ~/.codex/agents...")
	targetAgentDir := filepath.Join(c.CodexHome, "agents")
	if ok, err := c.prepareCodexAgentDir(targetAgentDir); err != nil {
		return err
	} else if ok {
		if err := c.generateCodexRoleFiles(targetAgentDir); err != nil {
			return err
		}
	}
	c.println("")
	c.println("Codex setup complete.")
	return nil
}

func (c Config) SetupClaudeAgents() error {
	c.println("Applying Claude Code agent setup...")
	if err := os.MkdirAll(c.ClaudeHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking Claude agent files into ~/.claude/agents...")
	target := filepath.Join(c.ClaudeHome, "agents")
	if ok, err := c.prepareClaudeAgentDir(target); err != nil {
		return err
	} else if ok {
		if err := c.createEntrySymlinks(filepath.Join(c.RepoRoot, "claude-agents"), target); err != nil {
			return err
		}
	}
	c.println("")
	c.println("Claude agent setup complete.")
	return nil
}

func (c Config) SetupCodexShell() error {
	c.println("Applying Codex shell helper setup...")
	if err := os.MkdirAll(c.CodexHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking Codex shell helper...")
	if err := c.createSymlink(filepath.Join(c.RepoRoot, "shell", "codex-profile-auto.zsh"), filepath.Join(c.CodexHome, "shell", "codex-profile-auto.zsh")); err != nil {
		return err
	}
	c.println("")
	c.println("Ensuring ~/.zshrc sources Codex shell helper...")
	if err := c.appendZshrcSource(filepath.Join(c.Home, ".zshrc")); err != nil {
		return err
	}
	c.println("")
	c.println("Codex shell helper setup complete.")
	return nil
}

func (c Config) BuildHooks() error {
	c.println("Building Go hook binaries...")
	if err := os.MkdirAll(filepath.Join(c.RepoRoot, "plugins", "ai-agent-config-guardrails", "hooks", "bin"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(c.RepoRoot, "plugins", "ai-agent-git-routing", "hooks", "bin"), 0o755); err != nil {
		return err
	}
	if err := c.runGo("test", "./..."); err != nil {
		return err
	}
	if err := c.runGo("build", "-o", filepath.Join(c.RepoRoot, "plugins", "ai-agent-config-guardrails", "hooks", "bin", "agent-config-guardrails"), "./cmd/agent-config-guardrails"); err != nil {
		return err
	}
	if err := c.runGo("build", "-o", filepath.Join(c.RepoRoot, "plugins", "ai-agent-git-routing", "hooks", "bin", "agent-git-routing"), "./cmd/agent-git-routing"); err != nil {
		return err
	}
	c.println("Built:")
	c.println("  plugins/ai-agent-config-guardrails/hooks/bin/agent-config-guardrails")
	c.println("  plugins/ai-agent-git-routing/hooks/bin/agent-git-routing")
	return nil
}

func (c Config) createSymlink(source, target string) error {
	if _, err := os.Lstat(source); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			c.printf("   ! Source not found, skipping: %s\n", source)
			return nil
		}
		return err
	}
	info, err := os.Lstat(target)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(target)
			if err != nil {
				return err
			}
			if current == source {
				c.printf("   = Symlink already correct: %s\n", target)
			} else {
				c.printf("   ! Symlink exists with different source: %s -> %s\n", target, current)
				c.println("     Skipping to avoid overwrite.")
			}
			return nil
		}
		c.printf("   ! Target exists and is not a symlink: %s\n", target)
		c.println("     Skipping to avoid overwrite.")
		return nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.Symlink(source, target); err != nil {
		return err
	}
	c.printf("   + Created symlink: %s -> %s\n", target, source)
	return nil
}

func (c Config) createSkillSymlinks(sourceDir, targetDir string) error {
	if !dirExists(sourceDir) {
		c.printf("   ! Skills source directory not found, skipping: %s\n", sourceDir)
		return nil
	}
	return c.createEntrySymlinks(sourceDir, targetDir)
}

func (c Config) createEntrySymlinks(sourceDir, targetDir string) error {
	if !dirExists(sourceDir) {
		c.printf("   ! Source directory not found, skipping: %s\n", sourceDir)
		return nil
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		if err := c.createSymlink(filepath.Join(sourceDir, entry.Name()), filepath.Join(targetDir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func (c Config) prepareCodexAgentDir(targetDir string) (bool, error) {
	legacySource := filepath.Join(c.RepoRoot, "agents")
	info, err := os.Lstat(targetDir)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(targetDir)
			if err != nil {
				return false, err
			}
			if current == legacySource {
				c.printf("   ! Legacy Codex agents symlink detected: %s -> %s\n", targetDir, current)
				c.println("     Remove that symlink and rerun install.sh so standalone agent TOML files can be generated into ~/.codex/agents/.")
				return false, nil
			}
		} else if !info.IsDir() {
			c.printf("   ! Target exists and is not a directory: %s\n", targetDir)
			c.println("     Skipping standalone Codex agent sync.")
			return false, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	return true, os.MkdirAll(targetDir, 0o755)
}

func (c Config) prepareClaudeAgentDir(targetDir string) (bool, error) {
	source := filepath.Join(c.RepoRoot, "claude-agents")
	info, err := os.Lstat(targetDir)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(targetDir)
			if err != nil {
				return false, err
			}
			if current == source {
				if err := os.Remove(targetDir); err != nil {
					return false, err
				}
				if err := os.MkdirAll(targetDir, 0o755); err != nil {
					return false, err
				}
				c.printf("   + Migrated directory symlink to real directory: %s\n", targetDir)
				return true, nil
			}
			c.printf("   ! Claude agents symlink exists with different source: %s -> %s\n", targetDir, current)
			c.println("     Skipping per-file sync to avoid overwrite.")
			return false, nil
		}
		if !info.IsDir() {
			c.printf("   ! Target exists and is not a directory: %s\n", targetDir)
			c.println("     Skipping Claude agent sync.")
			return false, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	return true, os.MkdirAll(targetDir, 0o755)
}

func (c Config) generateCodexRoleFiles(targetDir string) error {
	sourceDir := filepath.Join(c.RepoRoot, "config", "codex-agents")
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".toml" {
			continue
		}
		source := filepath.Join(sourceDir, entry.Name())
		target := filepath.Join(targetDir, entry.Name())
		rendered, err := c.renderRoleTemplate(source)
		if err != nil {
			return err
		}
		if ok, err := c.canWriteGeneratedRole(target, sourceDir); err != nil {
			return err
		} else if !ok {
			continue
		}
		if err := os.WriteFile(target, rendered, 0o644); err != nil {
			return err
		}
		c.printf("   + Generated role file: %s\n", target)
	}
	return nil
}

func (c Config) renderRoleTemplate(path string) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	replacements := map[string]string{
		"{{HOME}}":        c.Home,
		"{{CODEX_HOME}}":  c.CodexHome,
		"{{AGENTS_HOME}}": c.AgentsHome,
		"{{REPO_ROOT}}":   c.RepoRoot,
	}
	text := string(raw)
	for old, newValue := range replacements {
		text = strings.ReplaceAll(text, old, filepath.ToSlash(newValue))
	}
	var out bytes.Buffer
	out.WriteString(managedHeader)
	out.WriteString(text)
	return out.Bytes(), nil
}

func (c Config) canWriteGeneratedRole(target, sourceDir string) (bool, error) {
	info, err := os.Lstat(target)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return true, nil
		}
		return false, err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		current, err := os.Readlink(target)
		if err != nil {
			return false, err
		}
		if filepath.Dir(current) == sourceDir {
			if err := os.Remove(target); err != nil {
				return false, err
			}
			return true, nil
		}
		c.printf("   ! Role symlink exists with different source: %s -> %s\n", target, current)
		c.println("     Skipping to avoid overwrite.")
		return false, nil
	}
	if info.IsDir() {
		c.printf("   ! Role target exists and is a directory: %s\n", target)
		c.println("     Skipping to avoid overwrite.")
		return false, nil
	}
	raw, err := os.ReadFile(target)
	if err != nil {
		return false, err
	}
	if bytes.HasPrefix(raw, []byte(managedHeader)) {
		return true, nil
	}
	c.printf("   ! Role target exists and is not managed by this installer: %s\n", target)
	c.println("     Skipping to avoid overwrite.")
	return false, nil
}

func (c Config) appendZshrcSource(path string) error {
	const sourceLine = `[[ -r "$HOME/.codex/shell/codex-profile-auto.zsh" ]] && source "$HOME/.codex/shell/codex-profile-auto.zsh"`
	raw, err := os.ReadFile(path)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		raw = nil
	}
	if bytes.Contains(raw, []byte("codex-profile-auto.zsh")) {
		c.println("   = ~/.zshrc already sources Codex shell helper")
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	if len(raw) > 0 && !bytes.HasSuffix(raw, []byte("\n")) {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}
	_, err = f.WriteString("\n# Codex repo-managed shell helpers\n" + sourceLine + "\n")
	if err != nil {
		return err
	}
	c.println("   + Added Codex shell helper source to ~/.zshrc")
	return nil
}

func (c Config) runGo(args ...string) error {
	cmd := exec.Command("go", args...)
	cmd.Dir = filepath.Join(c.RepoRoot, "hooks-go")
	cmd.Stdout = c.Out
	cmd.Stderr = c.Out
	return cmd.Run()
}

func (c Config) printf(format string, args ...any) {
	fmt.Fprintf(c.Out, format, args...)
}

func (c Config) println(text string) {
	fmt.Fprintln(c.Out, text)
}

func envDefault(key, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return fallback
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func defaultRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	if filepath.Base(cwd) == "hooks-go" {
		return filepath.Dir(cwd), nil
	}
	return cwd, nil
}
