package agentconfig

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"ai-agent-config/hooks/internal/codexconfig"
)

const managedHeader = "# Generated by ai-agent-config. Do not edit directly; edit config/codex-agents/*.toml.\n"

type codexRoleManifest struct {
	MCPServers  []codexMCPServer           `json:"mcp_servers"`
	SkillGroups map[string][]string        `json:"skill_groups"`
	Roles       map[string]codexRoleConfig `json:"roles"`
}

type codexMCPServer struct {
	Name          string            `json:"name"`
	Command       string            `json:"command"`
	Args          []string          `json:"args"`
	EnabledTools  []string          `json:"enabled_tools"`
	DisabledTools []string          `json:"disabled_tools"`
	Env           map[string]string `json:"env"`
}

type codexRoleConfig struct {
	AllowedMCPServers   []string `json:"allowed_mcp_servers"`
	DisabledSkillGroups []string `json:"disabled_skill_groups"`
}

type Config struct {
	RepoRoot        string
	Home            string
	CodexHome       string
	ClaudeHome      string
	OpenCodeHome    string
	AntigravityHome string
	AgentsHome      string
	Out             io.Writer
	Now             func() time.Time
	LookPath        func(string) (string, error)
}

func NewConfig(repoRoot string, out io.Writer) (Config, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Config{}, err
	}
	if repoRoot == "" {
		repoRoot, err = defaultRepoRoot()
		if err != nil {
			return Config{}, err
		}
	}
	repoRoot, err = filepath.Abs(repoRoot)
	if err != nil {
		return Config{}, err
	}
	if out == nil {
		out = os.Stdout
	}
	antigravityHome := envDefault("ANTIGRAVITY_HOME", "")
	if antigravityHome == "" {
		antigravityHome = envDefault("GEMINI_HOME", filepath.Join(home, ".gemini"))
	}
	return Config{
		RepoRoot:        repoRoot,
		Home:            home,
		CodexHome:       envDefault("CODEX_HOME", filepath.Join(home, ".codex")),
		ClaudeHome:      envDefault("CLAUDE_HOME", filepath.Join(home, ".claude")),
		OpenCodeHome:    envDefault("OPENCODE_HOME", filepath.Join(home, ".config", "opencode")),
		AntigravityHome: antigravityHome,
		AgentsHome:      envDefault("AGENTS_HOME", filepath.Join(home, ".agents")),
		Out:             out,
		Now:             time.Now,
		LookPath:        exec.LookPath,
	}, nil
}

func (c Config) Install() error {
	c.println("Installing AI agent configuration...")
	c.printf("Config directory: %s\n", c.RepoRoot)
	c.println("")
	c.println("Creating symlinks...")

	configured := 0
	if dirExists(c.CodexHome) {
		configured++
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.CodexHome, "AGENTS.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Codex home not found, skipping: %s\n", c.CodexHome)
	}
	if dirExists(c.ClaudeHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.ClaudeHome, "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "CLAUDE.md"), filepath.Join(c.ClaudeHome, "CLAUDE.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Claude home not found, skipping: %s\n", c.ClaudeHome)
	}
	if dirExists(c.OpenCodeHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.OpenCodeHome, "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.OpenCodeHome, "AGENTS.md")); err != nil {
			return err
		}
		c.printOpenCodeSlimSkillSetup()
	} else {
		c.printf("   - OpenCode home not found, skipping: %s\n", c.OpenCodeHome)
	}
	if dirExists(c.AntigravityHome) {
		configured++
		if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.AntigravityHome, "antigravity-cli", "skills")); err != nil {
			return err
		}
		if err := c.createSymlink(filepath.Join(c.RepoRoot, "AGENTS.md"), filepath.Join(c.AntigravityHome, "GEMINI.md")); err != nil {
			return err
		}
	} else {
		c.printf("   - Antigravity CLI/Gemini home not found, skipping: %s\n", c.AntigravityHome)
	}

	c.println("")
	if configured == 0 {
		c.println("Warning: no supported home directories were found. No symlinks were created.")
	}
	if dirExists(c.CodexHome) {
		c.println("")
		if err := c.SetupCodexConfig(); err != nil {
			c.println("Warning: Codex base config setup failed; continuing with agent and shell setup.")
			c.println("         Run scripts/setup_codex_config.sh after resolving the reported config issue.")
		}
		c.println("")
		if err := c.SetupCodexAgents(); err != nil {
			return err
		}
		c.println("")
		if err := c.SetupCodexShell(); err != nil {
			return err
		}
		c.println("")
		if err := c.SetupCodexHooks(); err != nil {
			return err
		}
	}
	if dirExists(c.ClaudeHome) {
		c.println("")
		if err := c.SetupClaudeAgents(); err != nil {
			return err
		}
	}
	c.println("Installation complete.")
	c.println("")
	c.println("Next steps:")
	c.println("   1. Read README.md for usage.")
	c.println("   2. Update skills and config/codex-agents as needed.")
	c.println("   3. Run this script again after pulling updates.")
	return nil
}

func (c Config) printOpenCodeSlimSkillSetup() {
	for _, name := range []string{"oh-my-opencode-slim.jsonc", "oh-my-opencode-slim.json"} {
		configPath := filepath.Join(c.OpenCodeHome, name)
		if !fileExists(configPath) {
			continue
		}
		c.printf("   i oh-my-opencode-slim config detected: %s\n", configPath)
		c.printf("     Merge agent skill routing from: %s\n", filepath.Join(c.RepoRoot, "config", "opencode", "oh-my-opencode-slim-agent-skills.json"))
		c.println("     Existing slim config left unchanged.")
		return
	}
}

func (c Config) SetupCodexConfig() error {
	c.println("Applying Codex base config setup...")
	result, err := codexconfig.Apply(c.CodexHome, c.Now())
	if err != nil {
		c.printf("   ! Codex base config setup failed: %v\n", err)
		return err
	}
	if result.Changed {
		if result.BackupPath != "" {
			c.printf("   + Updated %s (backup: %s)\n", result.Path, result.BackupPath)
		} else {
			c.printf("   + Created %s\n", result.Path)
		}
	} else {
		c.printf("   = %s already has parent-safe defaults\n", result.Path)
	}
	if result.ProfileChanged {
		if result.ProfileBackupPath != "" {
			c.printf("   + Updated %s (backup: %s)\n", result.ProfilePath, result.ProfileBackupPath)
		} else {
			c.printf("   + Created %s\n", result.ProfilePath)
		}
	} else {
		c.printf("   = %s already has workspace-git profile\n", result.ProfilePath)
	}
	c.println("")
	c.println("Codex base config setup complete.")
	return nil
}

func (c Config) SetupCodexAgents() error {
	c.println("Applying Codex shared skills + standalone role-file setup...")
	if err := os.MkdirAll(c.CodexHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking shared Codex skills into ~/.agents/skills...")
	if err := c.createSkillSymlinks(filepath.Join(c.RepoRoot, "skills"), filepath.Join(c.AgentsHome, "skills")); err != nil {
		return err
	}
	c.println("")
	c.println("Generating standalone Codex role files into ~/.codex/agents...")
	targetAgentDir := filepath.Join(c.CodexHome, "agents")
	if ok, err := c.prepareCodexAgentDir(targetAgentDir); err != nil {
		return err
	} else if ok {
		if err := c.generateCodexRoleFiles(targetAgentDir); err != nil {
			return err
		}
	}
	c.println("")
	c.println("Codex setup complete.")
	return nil
}

func (c Config) SetupClaudeAgents() error {
	c.println("Applying Claude Code agent setup...")
	if err := os.MkdirAll(c.ClaudeHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking Claude agent files into ~/.claude/agents...")
	target := filepath.Join(c.ClaudeHome, "agents")
	if ok, err := c.prepareClaudeAgentDir(target); err != nil {
		return err
	} else if ok {
		if err := c.createEntrySymlinks(filepath.Join(c.RepoRoot, "claude-agents"), target); err != nil {
			return err
		}
	}
	c.println("")
	c.println("Claude agent setup complete.")
	return nil
}

func (c Config) SetupCodexShell() error {
	c.println("Applying Codex shell helper setup...")
	if err := os.MkdirAll(c.CodexHome, 0o755); err != nil {
		return err
	}
	c.println("")
	c.println("Linking Codex shell helper...")
	if err := c.createSymlink(filepath.Join(c.RepoRoot, "shell", "codex-profile-auto.zsh"), filepath.Join(c.CodexHome, "shell", "codex-profile-auto.zsh")); err != nil {
		return err
	}
	c.println("")
	c.println("Ensuring ~/.zshrc sources Codex shell helper...")
	if err := c.appendZshrcSource(filepath.Join(c.Home, ".zshrc")); err != nil {
		return err
	}
	c.println("")
	c.println("Codex shell helper setup complete.")
	return nil
}

func (c Config) BuildHooks() error {
	c.println("Building Go hook binaries...")
	if err := os.MkdirAll(filepath.Join(c.RepoRoot, "plugins", "ai-agent-config-guardrails", "hooks", "bin"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(c.RepoRoot, "plugins", "ai-agent-git-routing", "hooks", "bin"), 0o755); err != nil {
		return err
	}
	if err := c.runGo("test", "./..."); err != nil {
		return err
	}
	if err := c.runGo("build", "-o", filepath.Join(c.RepoRoot, "plugins", "ai-agent-config-guardrails", "hooks", "bin", "agent-config-guardrails"), "./cmd/agent-config-guardrails"); err != nil {
		return err
	}
	if err := c.runGo("build", "-o", filepath.Join(c.RepoRoot, "plugins", "ai-agent-git-routing", "hooks", "bin", "agent-git-routing"), "./cmd/agent-git-routing"); err != nil {
		return err
	}
	c.println("Built:")
	c.println("  plugins/ai-agent-config-guardrails/hooks/bin/agent-config-guardrails")
	c.println("  plugins/ai-agent-git-routing/hooks/bin/agent-git-routing")
	return nil
}

func (c Config) SetupCodexHooks() error {
	c.println("Applying Codex hook plugin setup...")
	if err := c.BuildHooks(); err != nil {
		return err
	}
	c.println("")
	c.println("Installing Codex hook plugins...")
	if c.codexMarketplaceConfigured() {
		c.println("   = Codex marketplace already configured: ai-agent-config")
	} else if err := c.runCodex("plugin", "marketplace", "add", c.RepoRoot); err != nil {
		return err
	}
	for _, plugin := range []string{
		"ai-agent-config-guardrails@ai-agent-config",
		"ai-agent-git-routing@ai-agent-config",
	} {
		if err := c.runCodex("plugin", "add", plugin); err != nil {
			return err
		}
	}
	c.println("")
	c.println("Codex hook plugin setup complete.")
	return nil
}

func (c Config) createSymlink(source, target string) error {
	if _, err := os.Lstat(source); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			c.printf("   ! Source not found, skipping: %s\n", source)
			return nil
		}
		return err
	}
	info, err := os.Lstat(target)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(target)
			if err != nil {
				return err
			}
			if current == source {
				c.printf("   = Symlink already correct: %s\n", target)
			} else {
				c.printf("   ! Symlink exists with different source: %s -> %s\n", target, current)
				c.println("     Skipping to avoid overwrite.")
			}
			return nil
		}
		c.printf("   ! Target exists and is not a symlink: %s\n", target)
		c.println("     Skipping to avoid overwrite.")
		return nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.Symlink(source, target); err != nil {
		return err
	}
	c.printf("   + Created symlink: %s -> %s\n", target, source)
	return nil
}

func (c Config) createSkillSymlinks(sourceDir, targetDir string) error {
	if !dirExists(sourceDir) {
		c.printf("   ! Skills source directory not found, skipping: %s\n", sourceDir)
		return nil
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		source := filepath.Join(sourceDir, entry.Name())
		if !entry.IsDir() || !fileExists(filepath.Join(source, "SKILL.md")) {
			c.printf("   - Skipping non-skill entry: %s\n", source)
			continue
		}
		if err := c.createSymlink(source, filepath.Join(targetDir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func (c Config) createEntrySymlinks(sourceDir, targetDir string) error {
	if !dirExists(sourceDir) {
		c.printf("   ! Source directory not found, skipping: %s\n", sourceDir)
		return nil
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		if err := c.createSymlink(filepath.Join(sourceDir, entry.Name()), filepath.Join(targetDir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}

func (c Config) prepareCodexAgentDir(targetDir string) (bool, error) {
	legacySource := filepath.Join(c.RepoRoot, "agents")
	info, err := os.Lstat(targetDir)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(targetDir)
			if err != nil {
				return false, err
			}
			if current == legacySource {
				c.printf("   ! Legacy Codex agents symlink detected: %s -> %s\n", targetDir, current)
				c.println("     Remove that symlink and rerun install.sh so standalone agent TOML files can be generated into ~/.codex/agents/.")
				return false, nil
			}
		} else if !info.IsDir() {
			c.printf("   ! Target exists and is not a directory: %s\n", targetDir)
			c.println("     Skipping standalone Codex agent sync.")
			return false, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	return true, os.MkdirAll(targetDir, 0o755)
}

func (c Config) prepareClaudeAgentDir(targetDir string) (bool, error) {
	source := filepath.Join(c.RepoRoot, "claude-agents")
	info, err := os.Lstat(targetDir)
	if err == nil {
		if info.Mode()&os.ModeSymlink != 0 {
			current, err := os.Readlink(targetDir)
			if err != nil {
				return false, err
			}
			if current == source {
				if err := os.Remove(targetDir); err != nil {
					return false, err
				}
				if err := os.MkdirAll(targetDir, 0o755); err != nil {
					return false, err
				}
				c.printf("   + Migrated directory symlink to real directory: %s\n", targetDir)
				return true, nil
			}
			c.printf("   ! Claude agents symlink exists with different source: %s -> %s\n", targetDir, current)
			c.println("     Skipping per-file sync to avoid overwrite.")
			return false, nil
		}
		if !info.IsDir() {
			c.printf("   ! Target exists and is not a directory: %s\n", targetDir)
			c.println("     Skipping Claude agent sync.")
			return false, nil
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	return true, os.MkdirAll(targetDir, 0o755)
}

func (c Config) generateCodexRoleFiles(targetDir string) error {
	sourceDir := filepath.Join(c.RepoRoot, "config", "codex-agents")
	manifest, err := loadCodexRoleManifest(filepath.Join(sourceDir, "role-manifest.json"))
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(sourceDir)
	if err != nil {
		return err
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name() < entries[j].Name() })
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".toml" {
			continue
		}
		source := filepath.Join(sourceDir, entry.Name())
		target := filepath.Join(targetDir, entry.Name())
		roleName := strings.TrimSuffix(entry.Name(), filepath.Ext(entry.Name()))
		rendered, err := c.renderRoleTemplate(source, roleName, manifest)
		if err != nil {
			return err
		}
		if ok, err := c.canWriteGeneratedRole(target, sourceDir); err != nil {
			return err
		} else if !ok {
			continue
		}
		if current, err := os.ReadFile(target); err == nil && bytes.Equal(current, rendered) {
			c.printf("   = Role file already current: %s\n", target)
			continue
		}
		if err := os.WriteFile(target, rendered, 0o644); err != nil {
			return err
		}
		c.printf("   + Generated role file: %s\n", target)
	}
	return nil
}

func (c Config) renderRoleTemplate(path, roleName string, manifest codexRoleManifest) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if strings.Contains(string(raw), "[mcp_servers.") {
		return nil, fmt.Errorf("%s contains [mcp_servers.*]; edit config/codex-agents/role-manifest.json instead", path)
	}
	if strings.Contains(string(raw), "[[skills.config]]") {
		return nil, fmt.Errorf("%s contains [[skills.config]]; edit config/codex-agents/role-manifest.json instead", path)
	}
	replacements := map[string]string{
		"{{HOME}}":        c.Home,
		"{{CODEX_HOME}}":  c.CodexHome,
		"{{AGENTS_HOME}}": c.AgentsHome,
		"{{REPO_ROOT}}":   c.RepoRoot,
	}
	text := string(raw)
	if declaredName, ok := roleNameFromTemplate(text); ok && declaredName != roleName {
		return nil, fmt.Errorf("%s declares role name %q, expected %q", path, declaredName, roleName)
	}
	text = renderPlaceholders(text, replacements)
	mcpServers, err := c.renderRoleMCPServers(roleName, manifest)
	if err != nil {
		return nil, err
	}
	skillToggles, err := manifest.renderRoleSkillToggles(roleName, replacements)
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString(managedHeader)
	out.WriteString(strings.TrimRight(text, "\n"))
	if mcpServers != "" {
		out.WriteString("\n\n")
		out.WriteString(mcpServers)
	}
	if skillToggles != "" {
		out.WriteString("\n\n")
		out.WriteString(skillToggles)
	}
	out.WriteString("\n")
	return out.Bytes(), nil
}

func loadCodexRoleManifest(path string) (codexRoleManifest, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return codexRoleManifest{}, err
	}
	var manifest codexRoleManifest
	if err := json.Unmarshal(raw, &manifest); err != nil {
		return codexRoleManifest{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := manifest.validate(); err != nil {
		return codexRoleManifest{}, fmt.Errorf("validate %s: %w", path, err)
	}
	return manifest, nil
}

func (m codexRoleManifest) validate() error {
	mcpNames := map[string]bool{}
	for _, server := range m.MCPServers {
		if strings.TrimSpace(server.Name) == "" {
			return errors.New("mcp server names must not be empty")
		}
		if mcpNames[server.Name] {
			return fmt.Errorf("duplicate mcp server %q", server.Name)
		}
		mcpNames[server.Name] = true
		if strings.TrimSpace(server.Command) == "" {
			return fmt.Errorf("mcp server %q command must not be empty", server.Name)
		}
	}
	if len(m.SkillGroups) == 0 {
		return errors.New("skill_groups must not be empty")
	}
	for groupName, paths := range m.SkillGroups {
		if strings.TrimSpace(groupName) == "" {
			return errors.New("skill group names must not be empty")
		}
		if len(paths) == 0 {
			return fmt.Errorf("skill group %q must contain at least one path", groupName)
		}
		for _, path := range paths {
			if strings.TrimSpace(path) == "" {
				return fmt.Errorf("skill group %q contains an empty path", groupName)
			}
		}
	}
	for roleName, role := range m.Roles {
		if strings.TrimSpace(roleName) == "" {
			return errors.New("role names must not be empty")
		}
		for _, serverName := range role.AllowedMCPServers {
			if !mcpNames[serverName] {
				return fmt.Errorf("role %q references unknown mcp server %q", roleName, serverName)
			}
		}
		for _, groupName := range role.DisabledSkillGroups {
			if _, ok := m.SkillGroups[groupName]; !ok {
				return fmt.Errorf("role %q references unknown skill group %q", roleName, groupName)
			}
		}
	}
	return nil
}

func (c Config) renderRoleMCPServers(roleName string, manifest codexRoleManifest) (string, error) {
	if len(manifest.MCPServers) == 0 {
		return "", nil
	}
	role := manifest.Roles[roleName]
	allowed := map[string]bool{}
	for _, name := range role.AllowedMCPServers {
		allowed[name] = true
	}
	var out bytes.Buffer
	for _, server := range manifest.MCPServers {
		if out.Len() > 0 {
			out.WriteString("\n\n")
		}
		out.WriteString(fmt.Sprintf("[mcp_servers.%s]\n", server.Name))
		out.WriteString(fmt.Sprintf("args = [%s]\n", quoteTOMLStrings(server.Args)))
		out.WriteString(fmt.Sprintf("command = %q\n", server.Command))
		out.WriteString(fmt.Sprintf("enabled = %v", allowed[server.Name] && c.commandAvailable(server.Command) && c.mcpConfigured(server.Name)))
		if len(server.EnabledTools) > 0 {
			out.WriteString(fmt.Sprintf("\nenabled_tools = [%s]", quoteTOMLStrings(server.EnabledTools)))
		}
		if len(server.DisabledTools) > 0 {
			out.WriteString(fmt.Sprintf("\ndisabled_tools = [%s]", quoteTOMLStrings(server.DisabledTools)))
		}
		if len(server.Env) > 0 {
			out.WriteString("\n\n")
			out.WriteString(fmt.Sprintf("[mcp_servers.%s.env]\n", server.Name))
			keys := make([]string, 0, len(server.Env))
			for key := range server.Env {
				keys = append(keys, key)
			}
			sort.Strings(keys)
			for index, key := range keys {
				if index > 0 {
					out.WriteString("\n")
				}
				out.WriteString(fmt.Sprintf("%s = %q", key, server.Env[key]))
			}
		}
	}
	return out.String(), nil
}

func (c Config) commandAvailable(command string) bool {
	lookPath := c.LookPath
	if lookPath == nil {
		lookPath = exec.LookPath
	}
	_, err := lookPath(command)
	return err == nil
}

func (c Config) mcpConfigured(name string) bool {
	configPath := filepath.Join(c.CodexHome, "config.toml")
	raw, err := os.ReadFile(configPath)
	if err != nil {
		return false
	}
	want := "mcp_servers." + name
	for _, line := range strings.Split(string(raw), "\n") {
		table, ok := tomlTableName(strings.TrimSpace(line))
		if ok && table == want {
			return true
		}
	}
	return false
}

func tomlTableName(line string) (string, bool) {
	if strings.HasPrefix(line, "[[") || !strings.HasPrefix(line, "[") || !strings.HasSuffix(line, "]") {
		return "", false
	}
	table := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, "["), "]"))
	return table, table != ""
}

func (m codexRoleManifest) renderRoleSkillToggles(roleName string, replacements map[string]string) (string, error) {
	role, ok := m.Roles[roleName]
	if !ok || len(role.DisabledSkillGroups) == 0 {
		return "", nil
	}
	var out bytes.Buffer
	for _, groupName := range role.DisabledSkillGroups {
		paths := m.SkillGroups[groupName]
		for _, path := range paths {
			if out.Len() > 0 {
				out.WriteString("\n\n")
			}
			out.WriteString("[[skills.config]]\n")
			out.WriteString(fmt.Sprintf("path = %q\n", renderPlaceholders(path, replacements)))
			out.WriteString("enabled = false")
		}
	}
	return out.String(), nil
}

func quoteTOMLStrings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func renderPlaceholders(text string, replacements map[string]string) string {
	for old, newValue := range replacements {
		text = strings.ReplaceAll(text, old, filepath.ToSlash(newValue))
	}
	return text
}

func roleNameFromTemplate(text string) (string, bool) {
	for _, line := range strings.Split(text, "\n") {
		trimmed := strings.TrimSpace(line)
		if !strings.HasPrefix(trimmed, "name") {
			continue
		}
		parts := strings.SplitN(trimmed, "=", 2)
		if len(parts) != 2 || strings.TrimSpace(parts[0]) != "name" {
			continue
		}
		value := strings.TrimSpace(parts[1])
		if len(value) >= 2 && value[0] == '"' && value[len(value)-1] == '"' {
			return value[1 : len(value)-1], true
		}
	}
	return "", false
}

func (c Config) canWriteGeneratedRole(target, sourceDir string) (bool, error) {
	info, err := os.Lstat(target)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return true, nil
		}
		return false, err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		current, err := os.Readlink(target)
		if err != nil {
			return false, err
		}
		if filepath.Dir(current) == sourceDir {
			if err := os.Remove(target); err != nil {
				return false, err
			}
			return true, nil
		}
		c.printf("   ! Role symlink exists with different source: %s -> %s\n", target, current)
		c.println("     Skipping to avoid overwrite.")
		return false, nil
	}
	if info.IsDir() {
		c.printf("   ! Role target exists and is a directory: %s\n", target)
		c.println("     Skipping to avoid overwrite.")
		return false, nil
	}
	raw, err := os.ReadFile(target)
	if err != nil {
		return false, err
	}
	if bytes.HasPrefix(raw, []byte(managedHeader)) {
		return true, nil
	}
	c.printf("   ! Role target exists and is not managed by this installer: %s\n", target)
	c.println("     Skipping to avoid overwrite.")
	return false, nil
}

func (c Config) appendZshrcSource(path string) error {
	const sourceLine = `[[ -r "$HOME/.codex/shell/codex-profile-auto.zsh" ]] && source "$HOME/.codex/shell/codex-profile-auto.zsh"`
	raw, err := os.ReadFile(path)
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		raw = nil
	}
	if bytes.Contains(raw, []byte("codex-profile-auto.zsh")) {
		c.println("   = ~/.zshrc already sources Codex shell helper")
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	if len(raw) > 0 && !bytes.HasSuffix(raw, []byte("\n")) {
		if _, err := f.WriteString("\n"); err != nil {
			return err
		}
	}
	_, err = f.WriteString("\n# Codex repo-managed shell helpers\n" + sourceLine + "\n")
	if err != nil {
		return err
	}
	c.println("   + Added Codex shell helper source to ~/.zshrc")
	return nil
}

func (c Config) runGo(args ...string) error {
	cmd := exec.Command("go", args...)
	cmd.Dir = filepath.Join(c.RepoRoot, "hooks-go")
	cmd.Stdout = c.Out
	cmd.Stderr = c.Out
	return cmd.Run()
}

func (c Config) runCodex(args ...string) error {
	if !c.commandAvailable("codex") {
		return errors.New("codex CLI is required to install Codex hook plugins")
	}
	cmd := exec.Command("codex", args...)
	cmd.Dir = c.RepoRoot
	cmd.Stdout = c.Out
	cmd.Stderr = c.Out
	return cmd.Run()
}

func (c Config) codexMarketplaceConfigured() bool {
	raw, err := os.ReadFile(filepath.Join(c.CodexHome, "config.toml"))
	if err != nil {
		return false
	}
	inMarketplace := false
	for _, line := range strings.Split(string(raw), "\n") {
		line := strings.TrimSpace(line)
		if table, ok := tomlTableName(line); ok {
			inMarketplace = table == "marketplaces.ai-agent-config"
			continue
		}
		if !inMarketplace {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok || strings.TrimSpace(key) != "source" {
			continue
		}
		source := strings.Trim(strings.TrimSpace(value), `"`)
		if filepath.Clean(source) == filepath.Clean(c.RepoRoot) {
			return true
		}
	}
	return false
}

func (c Config) printf(format string, args ...any) {
	fmt.Fprintf(c.Out, format, args...)
}

func (c Config) println(text string) {
	fmt.Fprintln(c.Out, text)
}

func envDefault(key, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(key)); value != "" {
		return value
	}
	return fallback
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func defaultRepoRoot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	if filepath.Base(cwd) == "hooks-go" {
		return filepath.Dir(cwd), nil
	}
	return cwd, nil
}
